language: python

python:
    - "pypy"
    - "2.7"
    - "3.2"
    - "3.3"

before_install:
    - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libz.so ~/virtualenv/python2.7/lib/

install:
    - pip install --quiet git+https://github.com/python-imaging/Pillow.git
    - sudo apt-get --quiet=2 install perceptualdiff

script:
    - ./test/test.py
    - ./test/test_coordinates.py
    - ./test/test_projections.py
    - ./test/test_gpx.py
    - ./test/test_projection_scale.py
    - ./test/test_random.py
    - ./test/test_gradients.py
