language: python

python:
    - "2.7"

install:
    - pip --quiet install pil

script:
    - ./heatmap.py -b black -p test/few-points -r 3 -W 22 -o output.ppm -P equirectangular
    - file output.ppm
