language: python

python:
    - "pypy"
    - "pypy3"
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

# for gdal
virtualenv:
   system_site_packages: true

before_install:
    - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libz.so ~/virtualenv/python2.7/lib/

install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then travis_retry pip install unittest2; fi
    - pip install coveralls
    - pip install --quiet git+https://github.com/python-imaging/Pillow.git
    - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
    - sudo apt-get update -qq
    - sudo apt-get --quiet=2 install perceptualdiff
    - sudo apt-get install libgdal1h
    - sudo apt-get install -y python-gdal

script:
    - coverage erase
    - coverage run --source heatmap --append ./test/test.py
    - coverage run --source heatmap --append ./test/test_coordinates.py
    - coverage run --source heatmap --append ./test/test_projections.py
    - coverage run --source heatmap --append ./test/test_gpx.py
    - coverage run --source heatmap --append ./test/test_projection_scale.py
    - coverage run --source heatmap --append ./test/test_random.py
    - coverage run --source heatmap --append ./test/test_gradients.py

    # gdal only installed for python 2.7
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then coverage run --source heatmap --append ./test/test_shp_file.py; fi

after_success:
    - coverage report
    - coveralls
    - pip install pep8 pyflakes
    - pep8 *.py
    - pyflakes *.py
    - pep8 test/*.py
    - pyflakes test/*.py
