language: python

python:
    - "pypy"
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

before_install:
    - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libz.so ~/virtualenv/python2.7/lib/

install:
  - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then travis_retry pip install unittest2; fi
    - pip install coveralls
    - pip install --quiet git+https://github.com/python-imaging/Pillow.git
    - sudo apt-get --quiet=2 install perceptualdiff

script:
    - coverage erase
    - coverage run --append ./test/test.py
    - coverage run --append ./test/test_coordinates.py
    - coverage run --append ./test/test_projections.py
    - coverage run --append ./test/test_gpx.py
    - coverage run --append ./test/test_projection_scale.py
    - coverage run --append ./test/test_random.py
    - coverage run --append ./test/test_gradients.py

after_success:
    - coverage report
    - coveralls
    - pip install pep8 pyflakes
    - pep8 *.py
    - pyflakes *.py
    - pep8 test/*.py
    - pyflakes test/*.py
